### ISSUE TITLE
Ability to filter very large files

### ISSUE THREAD

**Issue by jfreynik** [clue/php-stream-filter#28]
First I wanted to compliment the ReactPHP project and all the work you guys are doing - it's really awesome - I'm late to the game but am getting started with a project to compress and decompress large log (and other) files. 

This is a question and not an issue. 

I'm looking to use the zlib.deflate stream filter in an async manner since I'm dealing with rather large files and my search lead me here - looking at the source it looks like the Clue\StreamFilter\fun(...) function buffers the data read from the stream - I just wanted to double check that this could cause an out of memory exception on REALLY large files, yes? 

If so - I've got a few workarounds in mind but wanted to check with the source before I started down a different path.

Thank You!!

**Comment by clue** [comment]
Hi @jfreynik, thank you for your intro and for your most excellent question!

If you're looking to compress/decompress a stream of data with ReactPHP, I would highly recommend using https://github.com/clue/reactphp-zlib. That project builds on top of this project and in fact is part of the main motivation for creating this one in the first place.

To answer your question: Yes, memory limits are not an issue with either of these libraries. The logic implemented by this library is not exactly straight forward, so let me try to explain what's going on in the `fun()` function. When you invoke this function, it creates a new closure that you can use to pass some data to a built-in filter handler. It uses a temporary memory stream in order to access chunks of data that are returned by this stream, but it does not buffer anything beyond each chunk. This means that if you invoke it like the following, it will only ever keep small chunks in memory:

```php
$fn = fun(…);
$fn('hello');
$fn('world');
$fn();
```

I hope this helps :+1:
